#-------------------------------
# General Site Settings
#title: CloudOps
# logo: logo.svg # You can add own logo.
description: Personal Website and Blog about Cloud computing and cloud-native


#-------------------------------
# Author Settings
author:
  name: Bilal Jammal
  image: 01.jpg
  say-hello: Hello, I’m <strong>Bilal Jammal</strong>
  bio: Designs, Implements, and writes about <strong>Cloud</strong>, <strong>Cloud-Native</strong>, <strong>Cloud</strong>, and Systems. I share what I learn and would love to hear your feedback.


#-------------------------------
# Contact links
twitter: https://twitter.com/jammalbilal # Add your Twitter handle
#facebook: https://facebook.com/ # Add your Facebook handle
#dribbble: https://dribbble.com/ # Add your Dribbble handle
#instagram: https://instagram.com/ # Add your Instagram handle
#pinterest: https://pinterest.com/ # Add your Pinterest handle
linkedin: https://www.linkedin.com/in/bjammal/

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: bjammal # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
#instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
#instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
