# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
         
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests 
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v1.1.2

      - name: Publish newly added files to medium
        env: 
          MEDIUM_TOKEN: ${{ secrets.MEDIUM_TOKEN }}
          DEV_TO_TOKEN: ${{ secrets.DEV_TO_TOKEN }}
        run: |
          for file in ${{ steps.changed-files.outputs.added_files }}; do
            DIR=$(dirname "${file}")
            if [  $DIR == "_posts" ]; then
              echo "$file was added to the repository"
              echo "Publishing $file to Medium"
              python ./.github/scripts/publish_post_medium.py -i $file
              echo "Publishing $file to Dev.to"
              python ./.github/scripts/publish_post_devto.py -i $file
            fi
          done
          
      # - name: Publish newly added files to dev.to
      #   env: 
      #     MEDIUM_TOKEN: ${{ secrets.MEDIUM_TOKEN }}
      #   run: |
      #     for file in "${{ steps.changed-files.outputs.added_files }}"; do
      #       echo "$file was added, publishing it to dev.to"
      #       python ./.github/scripts/post.py $file
      #     done
      #     echo test, and deploy your project.
          
